configs:
  # - name: all_checks_on
  #   settings: {}
  # - name: type_check_off
  #   settings:
  #     check_settings:
  #       skip_type_check: true
  # - name: lint_off
  #   settings:
  #     check_settings:
  #       skip_lint: true
  # - name: tests_off
  #   settings:
  #     check_settings:
  #       skip_tests: true
  # - name: sqlmodel_off
  #   settings:
  #     check_settings:
  #       skip_sqlmodel: true
  - name: lint_and_type_check_off
    settings:
      check_settings:
        skip_lint: true
        skip_type_check: true
